### ISSUE TITLE
How to create lemonbar in bspwm?

### ISSUE THREAD

**Issue by ghost** [baskerville/xdo#10]
i use default panel lemonbar but in there only workspace indicator and clock.I will make my panel with use lemonbar then i create but use bash script like this link https://github.com/noptx/dutfiles/blob/master/bspwm/Alone/panel if i add /path/to/panel & in the end of bspwmrc display error when log out to tty:
.......
/path/to/panel : line 57: echo: write error: Broken pipe
/path/to/panel : line 57: echo: write error: Broken pipe
/path/to/panel : line 57: echo: write error: Broken pipe
/path/to/panel : line 57: echo: write error: Broken pipe
.......
I see panel,panel_bar and panel_colors in example bspwm have some var but i don't understand for edit the file.

**Comment by Anachron** [comment]
You did realize that this is not the BSPWM repository? 

Broken pipe means that your program (panel) ist still reading it, even though BSPWM is closed. You can fix this by closing the panel on BSPWM exit.
