### ISSUE TITLE
[question] Xdotool like `--sync` option?

### ISSUE THREAD

**Issue by Hibou57** [baskerville/xdo#16]
Either I’ve missed it or the documentation does not mention it (I’ve not installed ’xdo’, have just read the doc): `xdotool` has a `--sync` option to wait for a match instead of returning no match, when requesting a window information. This is convenient to be sure a window exist, that is, an application has its user interface ready, as an example.

I though may be `xdo` implicitly and always use the `--sync` behaviour of `xdotool`, but it's safer to ask.

**Comment by baskerville** [comment]
There's no such option yet.
