### ISSUE TITLE
How to get correct Keycodes?

### ISSUE THREAD

**Issue by juancarlospaco** [baskerville/xdo#25]
Hello, I made a library that uses XDo, I can not reliably find the correct Keycodes, I tried:

- https://wiki.archlinux.org/title/Map_scancodes_to_keycodes
- https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h
- https://gist.github.com/rickyzhang82/8581a762c9f9fc6ddb8390872552c250

I am on Linux all English with English keyboard, none of those lists has all the correct codes.

So far I tried number ranges and checking what key it triggers 1-by-1,
but thats bad because it may reboot, hibernate, turn off screen, etc.

I can not find out all UPPERCASE letters for example.
Do you know a list of correct keycodes?, or some Linux executable to find them?.

**Comment by SeerLite** [comment]
> I can not find out all UPPERCASE letters for example.

It's been a long time since I last did stuff with keycodes and keysyms but IIRC keycodes map to physical location on the keyboard, so modifications like uppercase and symbols won't have keycodes.

**Comment by veilm** [comment]
You probably don't need this anymore but you can use ``xev`` to view the keycodes. As SeerLite said, capital letters have the same kecyodes as their lowercase counterparts, and the Shift key doesn't seem to have a keycode, so I don't think it's possible to use xdo to input capital letters.
