### ISSUE TITLE
add interative modes where windows can be resized/moved with single keypresses

### ISSUE THREAD

**Issue by tb01110100** [baskerville/xdo#4]
Hello, I'd love it there was an option to enter an "interactive" mode where windows could be moved or resized with single hjkl or up/down/left/right keypresses, then quitting with ^C. Just a small idea.

**Comment by baskerville** [comment]
That's already possible.

Here's an example, taken straight from *sxhkd*'s manual:
```
super + m : {h,j,k,l}
	xdo move {-x -5,-y +5,-y -5,-x +5}
```

**Comment by tb01110100** [comment]
Eh, close enough. Thanks for responding.
