### ISSUE TITLE
Making panel on top of all windows except fullscreen

### ISSUE THREAD

**Issue by jamietanna** [baskerville/xdo#8]
Resubmitted from baskerville/bspwm#484.

I'm currently using the following code inside my panel, which is the same as found in [`bspwm/examples/panel/panel`](https://github.com/baskerville/bspwm/blob/44c5084/examples/panel/panel).

```bash
panel_bar < "$PANEL_FIFO" | lemonbar -n "$PANEL_WM_NAME" -g x$PANEL_HEIGHT -f "$PANEL_FONT_FAMILY" -F "$(bar_color_fg COLOR_BAR)" -B "$(bar_color_bg COLOR_BAR)" | while read line; do
	eval "$line"
done

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"
```

However, I'm finding that other applications, when fullscreened, remain _underneath_ the panel:
![2016-05-18-151435_508x85_scrot](https://cloud.githubusercontent.com/assets/3315059/15361877/41d0cffe-1d0b-11e6-950d-7640510ca2fa.png)

I have found a workaround that lowers the panel once, to just below a fullscreen screen:

```bash
if [ -n "$wid" ]; then
	xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"
	xdo lower "$wid"
fi
```

However, this issue does **not** work when using multiple monitors; on the second monitor, the rule is not applied:

![2016-05-18-152001_527x136_scrot](https://cloud.githubusercontent.com/assets/3315059/15362125/0b04504e-1d0c-11e6-9fb5-68bf350048fd.png)

Could this be a bug in xdo, or is it more likely me doing something wrong?

**Comment by baskerville** [comment]
Sorry, I should have been more explicit: this can't be an *xdo* bug.
