### ISSUE TITLE
`xdo id -d` doesn't print anything

### ISSUE THREAD

**Issue by onodera-punpun** [baskerville/xdo#9]
I'd expect it to print all windows on the current virtual desktop.

**Comment by baskerville** [comment]
I can't reproduce.

What window manager are you using?

**Comment by onodera-punpun** [comment]
openbox

**Comment by onodera-punpun** [comment]
Some more info: something like `xdo close -d` doesn't work either, so it's the `-d` that's faulty, and not the `id`.

**Comment by baskerville** [comment]
`-d` and `-D` rely on *_NET_WM_DESKTOP*.

What's the output of `xprop -id $(xdo id) _NET_WM_DESKTOP`?

**Comment by onodera-punpun** [comment]
I created some fork of your xtitle called xdesktop (https://github.com/onodera-punpun/xdesktop), which seems to relay on the same atoms as xdo, so I don't know why this happens.

```fish
/usr/ports/xorg/xorg-xprop xprop -id (xdo id) _NET_WM_DESKTOP
_NET_WM_DESKTOP(CARDINAL) = 0
# switching desktop now
/usr/ports/xorg/xorg-xprop xprop -id (xdo id) _NET_WM_DESKTOP
_NET_WM_DESKTOP(CARDINAL) = 1

```

**Comment by baskerville** [comment]
The problem probably comes from the fact that *Openbox* is a reparenting WM.

**Comment by baskerville** [comment]
This should be fixed by 6957a0f.

**Comment by onodera-punpun** [comment]
Yup, fixed. Thanks!

Bu the way, could you please tag a new release?

**Comment by baskerville** [comment]
Done.
